script: make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: N84e6bYi7w/TGcv8ts2cw6ESOxj3p/ThYrI+ZSWh7msIi7YM7hTLnC+evmGIguBLxauXVx787l3kWdT237Lzk6ukAuK1aHrMlCz5D3mbN5xy1QLVRmpYkxSwQ/TbZpB5oShbCMjm6z04xOQwA6WvLdrNCOIUE6JeY3Tj1/iPSSA=
  app:
    develop: itachi-presentation-stubulator01
